version: '3'

services:
  laravel:
    build:
      context: ./php
      dockerfile: Dockerfile.prod
    image: garmando/laravel-php
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: garmando/nginx-proxy
    container_name: nginx-proxy
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge